### ISSUE TITLE
Does MakeSharp support Packs?

### ISSUE THREAD

**Issue by mterwoord** [sapiens/MakeSharp#2]
Is there any way to make packs, like Scriptcs does? For example a pack pulling in git functionality, or other things?

**Comment by sapiens** [comment]
No, but I'm accepting a PR if you have the time to contribute

**Comment by mterwoord** [comment]
Well, it seems scriptcs does it differently than I'd personally like....
Scriptcs seems to be a generic tool for running scripts. Do you intend to have packs able to be redistributed by nuget?

**Comment by sapiens** [comment]
Are you referring to creating nuget packages?

**Comment by mterwoord** [comment]
My goal with a buildscript system (either MakeSharp, or custom-built..), is to have nuget packages which contain parts of scripts (or helper libraries, packs, whatever you name it) and have the final script use those to make builds.

**Comment by sapiens** [comment]
I understand now. While it looks useful, as this point I don't have the time to add new functionality to Make#

**Comment by mterwoord** [comment]
If you're interested in having what I want in Make#, I can spend time on it. 
See your email, are you available for chad?

**Comment by sapiens** [comment]
I've got the email, but I don't have time right now. Maybe we can talk in the w/e?

**Comment by mterwoord** [comment]
Sure, no rush. Didn't mean to be rude though.

Must say, that I've had a bit more thought over it, and now I think I can get something working pretty easy, need to think that over a bit more..
